In [1]:
import numpy as np

In [17]:
x = np.array([10,20,13,156,89,90])
y = np.array([[12,190,43,1000],[22,45,76,2],[1,2,3,4]])

In [18]:
print(x.shape)
print(y.shape)

(6,)
(3, 4)


In [19]:
print(x.size)
print(y.size)

6
12


In [20]:
print(x.dtype)
print(y.dtype)

int64
int64


In [26]:
# reshape
y.reshape(6,2)

array([[  12,  190],
       [  43, 1000],
       [  22,   45],
       [  76,    2],
       [   1,    2],
       [   3,    4]])

In [23]:
y

array([[  12,  190,   43, 1000],
       [  22,   45,   76,    2],
       [   1,    2,    3,    4]])

In [28]:
a=np.array([202,35,12,22,33,67])

In [32]:
b=np.array([[1000,2000],[3000,4000]])
c=np.array([[2,3]])

In [35]:
np.concatenate([b,c],axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [45]:
z=np.array([[2,9,5],[20,3,5],[2,3,6]])

In [46]:
z

array([[ 2,  9,  5],
       [20,  3,  5],
       [ 2,  3,  6]])

In [47]:
z.argmax(axis=0)

array([1, 0, 2])

In [48]:
z.argmax(axis=1)

array([1, 0, 2])

In [49]:
fourd=np.array([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]],
                [[[25,26,27,28],[29,30,31,32],[33,34,35,36]],[[37,38,39,40],[41,42,43,44],[45,46,47,48]]]])

In [50]:
fourd

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]],


       [[[25, 26, 27, 28],
         [29, 30, 31, 32],
         [33, 34, 35, 36]],

        [[37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]]]])

In [51]:
import pandas as pd

In [52]:
s1 = pd.Series([1,2,3,4,5],['one','two','three','four','five'])

In [53]:
s1

one      1
two      2
three    3
four     4
five     5
dtype: int64

In [54]:
s1.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [55]:
s2 = pd.Series([1,2,3,4,5])

In [56]:
s2

0    1
1    2
2    3
3    4
4    5
dtype: int64